// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockport

import (
	model "github.com/isutare412/web-memo/api/internal/core/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockEmbeddingEnqueuer is an autogenerated mock type for the EmbeddingEnqueuer type
type MockEmbeddingEnqueuer struct {
	mock.Mock
}

type MockEmbeddingEnqueuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingEnqueuer) EXPECT() *MockEmbeddingEnqueuer_Expecter {
	return &MockEmbeddingEnqueuer_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: _a0
func (_m *MockEmbeddingEnqueuer) Enqueue(_a0 model.EmbeddingJob) {
	_m.Called(_a0)
}

// MockEmbeddingEnqueuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockEmbeddingEnqueuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - _a0 model.EmbeddingJob
func (_e *MockEmbeddingEnqueuer_Expecter) Enqueue(_a0 interface{}) *MockEmbeddingEnqueuer_Enqueue_Call {
	return &MockEmbeddingEnqueuer_Enqueue_Call{Call: _e.mock.On("Enqueue", _a0)}
}

func (_c *MockEmbeddingEnqueuer_Enqueue_Call) Run(run func(_a0 model.EmbeddingJob)) *MockEmbeddingEnqueuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.EmbeddingJob))
	})
	return _c
}

func (_c *MockEmbeddingEnqueuer_Enqueue_Call) Return() *MockEmbeddingEnqueuer_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEmbeddingEnqueuer_Enqueue_Call) RunAndReturn(run func(model.EmbeddingJob)) *MockEmbeddingEnqueuer_Enqueue_Call {
	_c.Run(run)
	return _c
}

// EnqueueDelete provides a mock function with given fields: memoID
func (_m *MockEmbeddingEnqueuer) EnqueueDelete(memoID uuid.UUID) {
	_m.Called(memoID)
}

// MockEmbeddingEnqueuer_EnqueueDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueDelete'
type MockEmbeddingEnqueuer_EnqueueDelete_Call struct {
	*mock.Call
}

// EnqueueDelete is a helper method to define mock.On call
//   - memoID uuid.UUID
func (_e *MockEmbeddingEnqueuer_Expecter) EnqueueDelete(memoID interface{}) *MockEmbeddingEnqueuer_EnqueueDelete_Call {
	return &MockEmbeddingEnqueuer_EnqueueDelete_Call{Call: _e.mock.On("EnqueueDelete", memoID)}
}

func (_c *MockEmbeddingEnqueuer_EnqueueDelete_Call) Run(run func(memoID uuid.UUID)) *MockEmbeddingEnqueuer_EnqueueDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockEmbeddingEnqueuer_EnqueueDelete_Call) Return() *MockEmbeddingEnqueuer_EnqueueDelete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEmbeddingEnqueuer_EnqueueDelete_Call) RunAndReturn(run func(uuid.UUID)) *MockEmbeddingEnqueuer_EnqueueDelete_Call {
	_c.Run(run)
	return _c
}

// Results provides a mock function with no fields
func (_m *MockEmbeddingEnqueuer) Results() <-chan uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Results")
	}

	var r0 <-chan uuid.UUID
	if rf, ok := ret.Get(0).(func() <-chan uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan uuid.UUID)
		}
	}

	return r0
}

// MockEmbeddingEnqueuer_Results_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Results'
type MockEmbeddingEnqueuer_Results_Call struct {
	*mock.Call
}

// Results is a helper method to define mock.On call
func (_e *MockEmbeddingEnqueuer_Expecter) Results() *MockEmbeddingEnqueuer_Results_Call {
	return &MockEmbeddingEnqueuer_Results_Call{Call: _e.mock.On("Results")}
}

func (_c *MockEmbeddingEnqueuer_Results_Call) Run(run func()) *MockEmbeddingEnqueuer_Results_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingEnqueuer_Results_Call) Return(_a0 <-chan uuid.UUID) *MockEmbeddingEnqueuer_Results_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingEnqueuer_Results_Call) RunAndReturn(run func() <-chan uuid.UUID) *MockEmbeddingEnqueuer_Results_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingEnqueuer creates a new instance of MockEmbeddingEnqueuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingEnqueuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingEnqueuer {
	mock := &MockEmbeddingEnqueuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
