// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockport

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *MockPinger) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPinger_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPinger_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPinger_Expecter) Name() *MockPinger_Name_Call {
	return &MockPinger_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPinger_Name_Call) Run(run func()) *MockPinger_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPinger_Name_Call) Return(_a0 string) *MockPinger_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPinger_Name_Call) RunAndReturn(run func() string) *MockPinger_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: _a0
func (_m *MockPinger) Ping(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockPinger_Expecter) Ping(_a0 interface{}) *MockPinger_Ping_Call {
	return &MockPinger_Ping_Call{Call: _e.mock.On("Ping", _a0)}
}

func (_c *MockPinger_Ping_Call) Run(run func(_a0 context.Context)) *MockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPinger_Ping_Call) Return(_a0 error) *MockPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPinger_Ping_Call) RunAndReturn(run func(context.Context) error) *MockPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
