kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "webmemo-backup.fullname" . }}
  labels:
    {{- include "webmemo-backup.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
