apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "webmemo-backup.fullname" . }}
  labels:
    {{- include "webmemo-backup.labels" . | nindent 4 }}
spec:
  timeZone: {{ .Values.timeZone }}
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
            {{- with .Values.podAnnotations }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          labels:
            {{- include "webmemo-backup.labels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "webmemo-backup.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args: [ "-configs", "configs" ]
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              volumeMounts:
                - mountPath: /app/configs
                  name: configs-dir
                  readOnly: true
                {{- with .Values.volumeMounts }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
          volumes:
            - name: configs-dir
              configMap:
                name: {{ include "webmemo-backup.fullname" . }}
            {{- with .Values.volumes }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
