apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "postgres-headless.fullname" . }}
  labels:
    {{- include "postgres-headless.labels" . | nindent 4 }}
subsets:
  {{- .Values.endpoints.subsets | toYaml | nindent 2 }}
