with-expecter: true
packages:
  github.com/isutare412/web-memo/backup/internal/core/port:
    config:
      dir: "{{.InterfaceDir}}/mock{{.PackageName}}"
      outpkg: "mock{{.PackageName}}"
    interfaces:
      BackupExecutor:
      ObjectStorage:
      BackupService:
