apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "webmemo-router.fullname" . }}
  labels:
    {{- include "webmemo-router.labels" . | nindent 4 }}
spec:
  hosts:
  - memo.redshore.me
  gateways:
  - istio-system/ingress-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: {{ .Values.services.api }}
  - route:
    - destination:
        host: {{ .Values.services.ui }}
