// Code generated by ent, DO NOT EDIT.

package collaboration

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/isutare412/web-memo/api/internal/core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldUserID, v))
}

// MemoID applies equality check predicate on the "memo_id" field. It's identical to MemoIDEQ.
func MemoID(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldMemoID, v))
}

// Approved applies equality check predicate on the "approved" field. It's identical to ApprovedEQ.
func Approved(v bool) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldApproved, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNotIn(FieldUserID, vs...))
}

// MemoIDEQ applies the EQ predicate on the "memo_id" field.
func MemoIDEQ(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldMemoID, v))
}

// MemoIDNEQ applies the NEQ predicate on the "memo_id" field.
func MemoIDNEQ(v uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldMemoID, v))
}

// MemoIDIn applies the In predicate on the "memo_id" field.
func MemoIDIn(vs ...uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldIn(FieldMemoID, vs...))
}

// MemoIDNotIn applies the NotIn predicate on the "memo_id" field.
func MemoIDNotIn(vs ...uuid.UUID) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNotIn(FieldMemoID, vs...))
}

// ApprovedEQ applies the EQ predicate on the "approved" field.
func ApprovedEQ(v bool) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldApproved, v))
}

// ApprovedNEQ applies the NEQ predicate on the "approved" field.
func ApprovedNEQ(v bool) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldApproved, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.Collaboration {
	return predicate.Collaboration(sql.FieldLTE(FieldUpdateTime, v))
}

// HasCollaborator applies the HasEdge predicate on the "collaborator" edge.
func HasCollaborator() predicate.Collaboration {
	return predicate.Collaboration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CollaboratorTable, CollaboratorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollaboratorWith applies the HasEdge predicate on the "collaborator" edge with a given conditions (other predicates).
func HasCollaboratorWith(preds ...predicate.User) predicate.Collaboration {
	return predicate.Collaboration(func(s *sql.Selector) {
		step := newCollaboratorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMemo applies the HasEdge predicate on the "memo" edge.
func HasMemo() predicate.Collaboration {
	return predicate.Collaboration(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MemoTable, MemoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemoWith applies the HasEdge predicate on the "memo" edge with a given conditions (other predicates).
func HasMemoWith(preds ...predicate.Memo) predicate.Collaboration {
	return predicate.Collaboration(func(s *sql.Selector) {
		step := newMemoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Collaboration) predicate.Collaboration {
	return predicate.Collaboration(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Collaboration) predicate.Collaboration {
	return predicate.Collaboration(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Collaboration) predicate.Collaboration {
	return predicate.Collaboration(sql.NotPredicates(p))
}
