// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: webmemo/search.proto

package webmemopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMemosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords  []string `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"` // multiple keywords should be queried by OR.
	Fuzziness bool     `protobuf:"varint,2,opt,name=fuzziness,proto3" json:"fuzziness,omitempty"`
}

func (x *SearchMemosRequest) Reset() {
	*x = SearchMemosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webmemo_search_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMemosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemosRequest) ProtoMessage() {}

func (x *SearchMemosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webmemo_search_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemosRequest.ProtoReflect.Descriptor instead.
func (*SearchMemosRequest) Descriptor() ([]byte, []int) {
	return file_webmemo_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMemosRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchMemosRequest) GetFuzziness() bool {
	if x != nil {
		return x.Fuzziness
	}
	return false
}

type SearchMemosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hits []*SearchHit `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"` // order of hits is in descending order by score
}

func (x *SearchMemosResponse) Reset() {
	*x = SearchMemosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webmemo_search_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchMemosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemosResponse) ProtoMessage() {}

func (x *SearchMemosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webmemo_search_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemosResponse.ProtoReflect.Descriptor instead.
func (*SearchMemosResponse) Descriptor() ([]byte, []int) {
	return file_webmemo_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMemosResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoId string  `protobuf:"bytes,1,opt,name=memo_id,json=memoId,proto3" json:"memo_id,omitempty"`
	Score  float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webmemo_search_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_webmemo_search_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_webmemo_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHit) GetMemoId() string {
	if x != nil {
		return x.MemoId
	}
	return ""
}

func (x *SearchHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_webmemo_search_proto protoreflect.FileDescriptor

var file_webmemo_search_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x65, 0x62, 0x6d, 0x65, 0x6d, 0x6f, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x65, 0x62, 0x6d, 0x65, 0x6d, 0x6f, 0x22,
	0x4e, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x6f, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x75, 0x7a, 0x7a, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x22,
	0x3d, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x6f, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x68, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x6d, 0x65, 0x6d, 0x6f, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x69, 0x74, 0x52, 0x04, 0x68, 0x69, 0x74, 0x73, 0x22, 0x3a,
	0x0a, 0x09, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x59, 0x0a, 0x0d, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x77, 0x65, 0x62,
	0x6d, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x6f, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x65, 0x62, 0x6d, 0x65, 0x6d,
	0x6f, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4d, 0x65, 0x6d, 0x6f, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77,
	0x65, 0x62, 0x6d, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_webmemo_search_proto_rawDescOnce sync.Once
	file_webmemo_search_proto_rawDescData = file_webmemo_search_proto_rawDesc
)

func file_webmemo_search_proto_rawDescGZIP() []byte {
	file_webmemo_search_proto_rawDescOnce.Do(func() {
		file_webmemo_search_proto_rawDescData = protoimpl.X.CompressGZIP(file_webmemo_search_proto_rawDescData)
	})
	return file_webmemo_search_proto_rawDescData
}

var file_webmemo_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webmemo_search_proto_goTypes = []any{
	(*SearchMemosRequest)(nil),  // 0: webmemo.SearchMemosRequest
	(*SearchMemosResponse)(nil), // 1: webmemo.SearchMemosResponse
	(*SearchHit)(nil),           // 2: webmemo.SearchHit
}
var file_webmemo_search_proto_depIdxs = []int32{
	2, // 0: webmemo.SearchMemosResponse.hits:type_name -> webmemo.SearchHit
	0, // 1: webmemo.SearchService.SearchMemos:input_type -> webmemo.SearchMemosRequest
	1, // 2: webmemo.SearchService.SearchMemos:output_type -> webmemo.SearchMemosResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webmemo_search_proto_init() }
func file_webmemo_search_proto_init() {
	if File_webmemo_search_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webmemo_search_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SearchMemosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webmemo_search_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SearchMemosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webmemo_search_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SearchHit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webmemo_search_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webmemo_search_proto_goTypes,
		DependencyIndexes: file_webmemo_search_proto_depIdxs,
		MessageInfos:      file_webmemo_search_proto_msgTypes,
	}.Build()
	File_webmemo_search_proto = out.File
	file_webmemo_search_proto_rawDesc = nil
	file_webmemo_search_proto_goTypes = nil
	file_webmemo_search_proto_depIdxs = nil
}
