@memoId=<memoId>
@userId=<userId>

###
GET {{url}}/api/v1/google/sign-in

###
GET {{url}}/api/v1/google/sign-in/finish

###
GET {{url}}/api/v1/users/me
Authorization: Bearer {{idToken}}

###
POST {{url}}/api/v1/users/refresh-token
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/users/sign-out
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos?page=1&pageSize=10
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos/{{memoId}}
Authorization: Bearer {{idToken}}

###
POST {{url}}/api/v1/memos
Authorization: Bearer {{idToken}}

{
    "title": "Test Title",
    "content": "with some contents inside.",
    "tags": [
        "study",
        "development"
    ]
}

###
PUT {{url}}/api/v1/memos/{{memoId}}
Authorization: Bearer {{idToken}}

{
    "title": "Test Title 2",
    "content": "content is replaced.",
    "tags": [
        "study",
        "production"
    ]
}

###
POST {{url}}/api/v1/memos/{{memoId}}/publish
Authorization: Bearer {{idToken}}

{
    "publish": true
}

###
DELETE {{url}}/api/v1/memos/{{memoId}}
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos/{{memoId}}/tags
Authorization: Bearer {{idToken}}

###
PUT {{url}}/api/v1/memos/{{memoId}}/tags
Authorization: Bearer {{idToken}}

[]

###
GET {{url}}/api/v1/memos/{{memoId}}/subscribers/{{userId}}
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos/{{memoId}}/subscribers
Authorization: Bearer {{idToken}}

###
PUT {{url}}/api/v1/memos/{{memoId}}/subscribers/{{userId}}
Authorization: Bearer {{idToken}}

###
DELETE {{url}}/api/v1/memos/{{memoId}}/subscribers/{{userId}}
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/tags?kw=
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos/{{memoId}}/collaborators/{{userId}}
Authorization: Bearer {{idToken}}

###
GET {{url}}/api/v1/memos/{{memoId}}/collaborators
Authorization: Bearer {{idToken}}

###
PUT {{url}}/api/v1/memos/{{memoId}}/collaborators/{{userId}}
Authorization: Bearer {{idToken}}

###
POST {{url}}/api/v1/memos/{{memoId}}/collaborators/{{userId}}/authorize
Authorization: Bearer {{idToken}}

{
    "approve": true
}

###
DELETE {{url}}/api/v1/memos/{{memoId}}/collaborators/{{userId}}
Authorization: Bearer {{idToken}}
